// ==========================================
// SUFFA KÜLLİYATI - VERİ DEPOSU (veri.js)
// Kitap: Kur'ân Bilinci Dersleri
// Yazar: Muhammed Emin Yıldırım
// ==========================================

window.QUOTES = [
    {
        tr: "İhlas, aradan dünyayı çıkarıp sadece O'nu (cc) görmektir...",
        ing: "Ikhlas is removing the Dunya from between and seeing only Him (cc)...",
        alm: "Ikhlas bedeutet, die Dunya dazwischen zu entfernen und nur Ihn (cc) zu sehen...",
        arp: "الإخلاص هو إزالة الدنيا من البين ورؤيته سبحانه وتعالى فقط..."
    },
    {
        tr: "Beşerin derdine derman olur ancak Kur'ân; onsuz artık canavardan da beterdir insan.",
        ing: "Only the Quran can be the remedy for humanity's pain; without it, man is worse than a beast.",
        alm: "Nur der Koran kann das Heilmittel für den Schmerz der Menschheit sein; ohne ihn ist der Mensch schlimmer als ein Biest.",
        arp: "القرآن هو دواء آلام البشر؛ وبدونه يصبح الإنسان أسوأ من الوحش."
    }
];

window.ENCYCLOPEDIA = {
    'Seyyah Melekleri': 'Yeryüzünde dolaşarak Allah\'ı zikreden meclisleri ve kulları arayan nurani varlıklar.',
    'Refîk-i A\'lâ': 'En yüce dost, Allah (cc). Efendimiz\'in (sas) vefat anında dudaklarından dökülen son ifadedir.',
    'Mübelliğ': 'İlâhî vahyi insanlara eksiksiz bir şekilde ulaştıran, tebliğ eden peygamber.',
    'Asr-ı Saadet': 'İnsanlığın en mutlu dönemi, Peygamber Efendimiz\'in (sas) yaşadığı asır.',
    'Câhiliye': 'İslâm\'dan önceki bilgisizlik, putperestlik ve karanlık dönem.',
    'Kelâmullah': 'Allah\'ın kelâmı, sözü. Kur\'ân-ı Kerîm\'in en temel isimlerinden biridir.',
    'Kelâm-ı Ezelî': 'Başlangıcı olmayan, zamandan münezzeh olan Allah\'ın kelâmı.',
    'Şakî': 'Dünya ve ahirette bedbaht olan, haktan sapan kimse.',
    'Saîd': 'Allah\'ın rızasını kazanmış, ahirette mutluluğa eren bahtiyar kimse.',
    'İtminan': 'Kalbin şüphelerden arınarak tam bir huzur ve sükûna ermesi hâli.',
    'Sekînet': 'Allah tarafından müminlerin kalbine indirilen güven, huzur ve sükûnet hâli.',
    'Furkan': 'Hakkı batıldan, doğruyu yanlıştan ayıran; Kur\'ân-ı Kerîm\'in isimlerinden biri.',
    'Suffa Meclisleri': 'İlim, ahlâk ve Kur\'ân şuurunu kuşanmak maksadıyla bir araya gelen ilim halkaları.'
};

window.ASSISTANT_DB = {
    'ihlas': "Kıymetli kardeşlerim, ihlas demek; ameli işlerken aradan dünyayı ve insanları çıkarıp sadece Allah'ın rızasını gözetmek demektir.",
    'sabr': "Sabır, musibetin ilk anındaki duruştur. Vahyin gölgesinde direnmek ve teslimiyeti kuşanmaktır.",
    'kuran': "Kur'ân, kalplerin ilacı, zihinlerin dermanı, dillerin ise fermanıdır. O, Allah ile dertleşmenin en yüce makamıdır."
};

window.KULLIYAT_VERISI = {
    kuran: { 
        title: "Kur'ân Bilinci", 
        subtitle: "Hayat Kitabımız", 
        symbol: '✧', 
        chapters: [
            {
                id: 'k0_1',
                title_tr: "Nebevî Bir Müjde ve İthaf",
                title_ing: "A Prophetic Glad Tiding and Dedication",
                title_alm: "Eine Prophetische Frohe Botschaft und Widmung",
                title_arp: "بشارة نبوية وإهداء",
                tr: "Ebû Hüreyre'nin (ra) naklettiğine göre Efendimiz (sas) buyurmuşlardır ki: Allah Teâlâ'nın yollarda dolaşıp Allah'ı ananları tespit eden Seyyah Melekleri vardır. Bunlar Cenâb-ı Hakk'ı anan bir topluluğa rastladıkları zaman birbirlerine, 'Gelin! Aradıklarınız burada!' diye seslenirler ve o meclistekileri dünya semâsına varıncaya kadar kanatlarıyla çevirip kuşatırlar. Bunun üzerine Allah Teâlâ, meleklerden daha iyi bildiği hâlde yine de onlara, 'Kullarım ne diyor?' diye sorar. Melekler, 'Sübhanallah, diyerek ulûhiyyetine yakışmayan sıfatlardan tenzih ediyorlar. Allâhu ekber, diyerek tekbir getiriyorlar. Elhamdullillah, diyerek Sana hamdediyorlar ve Senin yüceliğini dile getiriyorlar.' derler. Konuşma şöyle devam eder:\n\n– Peki onlar beni gördüler mi ki?\n– Hayır, vallahi seni görmediler.\n– Beni görselerdi ne yaparlardı?\n– Şayet seni görselerdi sana daha çok ibadet ederler, şanını daha fazla yüceltirler, ulûhiyyetine yakışmayan sıfatlardan seni daha çok tenzih ederlerdi.\n– Kullarım benden ne istiyorlar?\n– Cennet istiyorlar.\n– Cenneti görmüşler mi?\n– Hayır, yâ Rabbi! Vallahi onlar cenneti görmediler.\n– Ya cenneti görseler ne yaparlardı?\n– Şayet cenneti görselerdi onu daha büyük bir iştiyakla isterlerdi, onu elde etmek için büyük gayret sarf ederlerdi.\n– Onlar bana neyden sığınıyorlar?\n– Cehennemden sığınıyorlar.\n– Peki, cehennemi gördüler mi?\n– Hayır, vallahi onlar cehennemi görmediler.\n– Ya görselerdi ne yaparlardı?\n– Şayet cehennemi görselerdi ondan daha çok kaçarlar, ondan pek fazla korkarlardı.\n\nBunun üzerine Allah Teâlâ, meleklerine, 'Sizi şahit tutarak söylüyorum ki ben bu hâlde olan kullarımı bağışladım.' buyurur. Meleklerden biri, 'Onların arasında bulunan falan kimse esasen onlardan değildir. O buraya bir iş için gelip oturmuştu.' deyince Allah Teâlâ şöyle buyurur: 'Orada oturanlar öyle iyi kimselerdir ki onların arasında bulunan da asla Şakî olmaz.' [Buhârî, 'Daavât', 66].\n\nBu nebevî müjdeye nail olmak için bir araya gelen tüm Suffa Meclisleri talebe ve muallimlerine ithaf olunur...",
                ing: "According to the narration of Abu Hurayrah (ra), our Master (pbuh) said: Allah the Exalted has Seyyah Melekleri (roaming angels) who travel the paths seeking those who remember Allah. When they find a gathering remembering Allah, they call out to one another, 'Come! What you are looking for is here!' and they surround that gathering with their wings up to the lowest heaven. Then Allah the Exalted, though He knows better than the angels, asks them: 'What are My servants saying?' The angels reply, 'They are glorifying You saying Subhanallah, they are magnifying You saying Allahu Akbar, and they are praising You saying Alhamdulillah.' The conversation continues:\n\n– Have they seen Me?\n– No, by Allah, they have not seen You.\n– What would they do if they saw Me?\n– If they saw You, they would worship You even more, glorify Your majesty even more, and exalt You far more from attributes unbefitting Your divinity.\n– What are My servants asking of Me?\n– They are asking for Jannah (Paradise).\n– Have they seen Jannah?\n– No, O Rabb! By Allah, they have not seen Jannah.\n– What would they do if they saw Jannah?\n– If they saw Jannah, they would desire it with an even greater passion, and strive with immense effort to attain it.\n– From what are they seeking refuge in Me?\n– They are seeking refuge from Jahannam (Hellfire).\n– Well, have they seen Jahannam?\n– No, by Allah, they have not seen Jahannam.\n– What would they do if they had seen it?\n– If they had seen Jahannam, they would flee from it even more, and fear it far more.\n\nUpon this, Allah the Exalted commands His angels: 'I make you witnesses that I have forgiven My servants who are in this state.' One of the angels says, 'There is someone among them who is not actually one of them. He just came and sat there for some other business.' Allah the Exalted then decrees: 'Those sitting there are such good people that anyone who sits among them shall never be a Şakî (deprived).' [Bukhari, Da'awat, 66].\n\nDedicated to all the students and teachers of the Suffa Meclisleri who come together to attain this Prophetic glad tiding...",
                alm: "Nach der Überlieferung von Abu Hurayrah (ra) sagte unser Prophet (saw): Allah der Erhabene hat Seyyah Melekleri (umherziehende Engel), die auf den Wegen reisen und jene suchen, die Allah gedenken. Wenn sie eine Versammlung finden, die Allah gedenken, rufen sie einander zu: 'Kommt! Was ihr sucht, ist hier!' und sie umgeben diese Versammlung mit ihren Flügeln bis zum untersten Himmel. Dann fragt Allah der Erhabene sie, obwohl Er es besser weiß als die Engel: 'Was sagen Meine Diener?' Die Engel antworten: 'Sie preisen Dich und sagen Subhanallah, sie verherrlichen Dich und sagen Allahu Akbar, und sie loben Dich und sagen Alhamdulillah.' Das Gespräch geht wie folgt weiter:\n\n– Haben sie Mich gesehen?\n– Nein, bei Allah, sie haben Dich nicht gesehen.\n– Was würden sie tun, wenn sie Mich sehen würden?\n– Wenn sie Dich sehen würden, würden sie Dich noch mehr anbeten, Deine Majestät noch mehr preisen und Dich noch mehr von Eigenschaften freisprechen, die Deiner Göttlichkeit nicht angemessen sind.\n– Was verlangen Meine Diener von Mir?\n– Sie bitten um Jannah (das Paradies).\n– Haben sie Jannah gesehen?\n– Nein, o Rabb! Bei Allah, sie haben Jannah nicht gesehen.\n– Was würden sie tun, wenn sie Jannah sehen würden?\n– Wenn sie Jannah sehen würden, würden sie es mit noch größerer Leidenschaft begehren und sich mit immenser Anstrengung bemühen, es zu erreichen.\n– Wovor suchen sie Zuflucht bei Mir?\n– Sie suchen Zuflucht vor Jahannam (der Hölle).\n– Nun, haben sie Jahannam gesehen?\n– Nein, bei Allah, sie haben Jahannam nicht gesehen.\n– Was würden sie tun, wenn sie es gesehen hätten?\n– Wenn sie Jahannam gesehen hätten, würden sie noch mehr davor fliehen und es noch viel mehr fürchten.\n\nDaraufhin befiehlt Allah der Erhabene Seinen Engeln: 'Ich mache euch zu Zeugen, dass Ich Meinen Dienern, die in diesem Zustand sind, vergeben habe.' Einer der Engel sagt: 'Da ist jemand unter ihnen, der eigentlich nicht zu ihnen gehört. Er kam nur für ein anderes Geschäft und setzte sich dorthin.' Allah der Erhabene bestimmt dann: 'Diejenigen, die dort sitzen, sind so gute Menschen, dass jeder, der unter ihnen sitzt, niemals ein Şakî (unglücklich) sein wird.' [Bukhari, Da'awat, 66].\n\nGewidmet allen Schülern und Lehrern der Suffa Meclisleri, die zusammenkommen, um diese prophetische frohe Botschaft zu erlangen...",
                arp: "عن أبي هريرة رضي الله عنه، عن النبي صلى الله عليه وسلم قال: إن لله ملائكة يطوفون في الطرق (Seyyah Melekleri) يلتمسون أهل الذكر، فإذا وجدوا قوماً يذكرون الله تنادوا: هلموا إلى حاجتكم! قال: فيحفونهم بأجنحتهم إلى السماء الدنيا. قال: فيسألهم ربهم، وهو أعلم منهم: ما يقول عبادي؟ قال: يقولون: يسبحونك، ويكبرونك، ويحمدونك، ويمجدونك. قال: فيقول:\n\n– هل رأوني؟\n– قال: يقولون: لا والله ما رأوك.\n– قال: فيقول: وكيف لو رأوني؟\n– قال: يقولون: لو رأوك كانوا أشد لك عبادة، وأشد لك تمجيداً، وأكثر لك تسبيحاً.\n– قال: يقول: فما يسألوني؟\n– قال: يسألونك الجنة.\n– قال: يقول: وهل رأوها؟\n– قال: يقولون: لا والله يا رب ما رأوها.\n– قال: يقول: فكيف لو أنهم رأوها؟\n– قال: يقولون: لو أنهم رأوها كانوا أشد عليها حرصاً، وأشد لها طلباً، وأعظم فيها رغبة.\n– قال: فمم يتعوذون؟\n– قال: يقولون: من النار.\n– قال: يقول: وهل رأوها؟\n– قال: يقولون: لا والله يا رب ما رأوها.\n– قال: يقول: فكيف لو رأوها؟\n– قال: يقولون: لو رأوها كانوا أشد منها فراراً، وأشد لها مخافة.\n\nقال: فيقول: فأشهدكم أني قد غفرت لهم. قال: يقول ملك من الملائكة: فيهم فلان ليس منهم، إنما جاء لحاجة. قال: هم الجلساء لا يكون جليسهم شقياً (Şakî). [رواه البخاري، الدعوات، 66].\n\nإهداء إلى جميع طلاب ومعلمي مجالس الصفة (Suffa Meclisleri) الذين يجتمعون لنيل هذه البشارة النبوية..."
            },
            {
                id: 'k0_2',
                title_tr: "Söz Başı",
                title_ing: "Foreword (Söz Başı)",
                title_alm: "Vorwort (Söz Başı)",
                title_arp: "مقدمة (كلمة البداية)",
                tr: "Yıl: 632. Bir cuma günü ve arefe. Yer: Arafat... Binlerin, yüz binlerin dua dua yakardığı mârifet meydanı... Mübarek bakışlarını Refîk-i A'lâ'ya çevirmiş olan âlemlerin rahmet vesilesi, her konuşmasını 'Belki bugünden sonra bir daha görüşemeyebiliriz!' [İbn Hişâm, Sîre, 4/250] diye bitiriyor. 23 yıl önce Hira'da 'İkra' ile başlayan süreç, şimdi Arafat'ta 'el-Yevme' diye nihayete eriyor...\n\nKur'ân'ın Mübelliği konuşuyor: 'Size sarıldığınız müddetçe asla sapmayacağınız iki ağır emanet bırakıyorum. Onlardan biri Allah'ın kitabı, diğeri ise benim sünnetimdir...' [Mâlik b. Enes, Muvatta, 'Kader', 3]. Allah'ın kitabı: Kelâmullah... Resûl'ün (sas) sünneti: O yüce kelâmın hayata dönüşmüş şekli... Biri satırlardaki Kur'ân, diğeri hayatın içindeki Kur'ân... Biri asıl, diğeri usul... Biri kaynak, diğeri ırmak... Hakkıyla o kaynağa sarılan ve ırmağa dalan, milâdî 6. asırda sahâbe olarak çıktı...\n\nÇünkü bu kitap mûcize bir kitap... Harfleriyle, kelimeleriyle, cümleleriyle, ölçülü lafzıyla, mânanın hakkını vermesiyle, meydan okumasıyla, nazmıyla, belâgatiyle, fesahatiyle ve daha yüzlerce özelliğiyle mûcize bir kitap... İnsan yetiştirmesiyle, toplumu dönüştürmesiyle, Şakîlerden Saîdler, cahillerden âlimler, inkârcılardan müminler, nankörlerden şâkirler, merhametsizlerden halimler, hazcılardan zahitler yetiştirmesiyle mûcize bir kitap...\n\nCâhiliye bataklığını Asr-ı Saadet'e, çöl adamlarını medeniyet havzasına, kör taassupları hikmet membaına, şehvet düşkünlerini iffet kahramanına dönüştüren mûcize bir kitap...",
                ing: "Year: 632. A Friday and the day of Arafah. Location: Arafat... The gathering place of Marifah where hundreds of thousands passionately supplicate... The mercy to the worlds, who has turned his blessed gaze to Refîk-i A'lâ, ends every speech saying, 'Perhaps after this day we may not meet again!' [Ibn Hisham, Sirah, 4/250]... The process that started with 'Iqra' in Hira 23 years ago is now concluding with 'Al-Yawma' in Arafat...\n\nThe Mübelliğ of the Quran speaks: 'I leave you two weighty trusts, as long as you hold fast to them you will never go astray. One is the Book of Allah, and the other is my Sunnah...' [Malik b. Anas, Muwatta, 'Qadar', 3]. The Book of Allah: Kelâmullah... The Sunnah of the Messenger (pbuh): The embodiment of that exalted word in life... One is the Quran in lines, the other is the Quran in life... One is the foundation, the other is the method... One is the source, the other is the river... Those who truly held onto that source and dove into that river emerged as the Sahaba in the 6th century AD...\n\nBecause this book is a miraculous book... With its letters, words, sentences, measured expressions, fulfilling of meaning, its challenge, its rhythm, eloquence, and hundreds of other features, it is a miraculous book... It is a miraculous book that raises humans, transforms society, breeds the Saîd from the Şakî, scholars from the ignorant, believers from deniers, the grateful from the ungrateful, the gentle from the merciless, and ascetics from hedonists...\n\nA miraculous book that transformed the swamp of Câhiliye into the Asr-ı Saadet, desert men into a basin of civilization, blind bigotry into a spring of wisdom, and victims of lust into heroes of chastity...",
                alm: "Jahr: 632. Ein Freitag und der Tag von Arafah. Ort: Arafat... Der Versammlungsort der Marifah, an dem Hunderttausende inständig flehen... Die Barmherzigkeit für die Welten, der seinen gesegneten Blick auf Refîk-i A'lâ gerichtet hat, beendet jede Rede mit den Worten: 'Vielleicht werden wir uns nach diesem Tag nicht wiedersehen!' [Ibn Hisham, Sirah, 4/250]... Der Prozess, der vor 23 Jahren mit 'Iqra' in Hira begann, endet nun mit 'Al-Yawma' in Arafat...\n\nDer Mübelliğ des Korans spricht: 'Ich hinterlasse euch zwei gewichtige anvertraute Güter, solange ihr daran festhaltet, werdet ihr niemals in die Irre gehen. Das eine ist das Buch Allahs und das andere ist meine Sunnah...' [Malik b. Anas, Muwatta, 'Qadar', 3]. Das Buch Allahs: Kelâmullah... Die Sunnah des Gesandten (saw): Die Verkörperung dieses erhabenen Wortes im Leben... Das eine ist der Koran in Zeilen, das andere ist der Koran im Leben... Das eine ist das Fundament, das andere ist die Methode... Das eine ist die Quelle, das andere ist der Fluss... Diejenigen, die sich wahrhaftig an diese Quelle hielten und in diesen Fluss eintauchten, traten im 6. Jahrhundert als Sahaba hervor...\n\nDenn dieses Buch ist ein wunderbares Buch... Mit seinen Buchstaben, Wörtern, Sätzen, maßvollen Ausdrücken, der Erfüllung von Bedeutung, seiner Herausforderung, seinem Rhythmus, seiner Beredsamkeit und Hunderten anderer Merkmale ist es ein wunderbares Buch... Es ist ein wunderbares Buch, das Menschen erzieht, die Gesellschaft transformiert, den Saîd aus dem Şakî, Gelehrte aus den Unwissenden, Gläubige aus Leugnern, Dankbare aus Undankbaren, Sanftmütige aus Barmherzigen und Asketen aus Hedonisten hervorbringt...\n\nEin wunderbares Buch, das den Sumpf der Câhiliye in das Asr-ı Saadet, Wüstenmänner in ein Becken der Zivilisation, blinden Fanatismus in eine Quelle der Weisheit und Opfer der Lust in Helden der Keuschheit verwandelte...",
                arp: "العام: 632. يوم جمعة ويوم عرفة. المكان: عرفات... ميدان المعرفة حيث يتضرع مئات الآلاف بحرارة... رحمة للعالمين، الذي وجه نظره المبارك إلى الرفيق الأعلى (Refîk-i A'lâ)، ينهي كل خطاباته قائلاً: 'لعلي لا ألقاكم بعد عامي هذا!' [ابن هشام، السيرة، 4/250]... العملية التي بدأت بـ 'اقرأ' في حراء قبل 23 عامًا تختتم الآن بـ 'اليوم' في عرفات...\n\nيتحدث مُبلِّغ (Mübelliğ) القرآن: 'تركت فيكم أمرين لن تضلوا ما تمسكتم بهما. كتاب الله وسنتي...' [مالك بن أنس، الموطأ، القدر، 3]. كتاب الله: كلام الله (Kelâmullah)... وسنة الرسول (صلى الله عليه وسلم): تجسيد ذلك الكلام الجليل في الحياة... أحدهما القرآن في السطور، والآخر القرآن في الحياة... أحدهما الأصل، والآخر المنهج... أحدهما النبع، والآخر النهر... أولئك الذين تمسكوا بحق بذلك النبع وغاصوا في ذلك النهر ظهروا كصحابة في القرن السادس الميلادي...\n\nلأن هذا الكتاب كتاب معجز... بحروفه وكلماته وجمله وتعبيراته الموزونة واستيفاء المعنى وتحديه وإيقاعه وبلاغته ومئات الميزات الأخرى، فهو كتاب معجز... إنه كتاب معجز يربي الإنسان، ويحول المجتمع، ويخرج السعيد (Saîd) من الشقي (Şakî)، والعلماء من الجهال، والمؤمنين من المنكرين، والشاكرين من الجاحدين، والحلماء من القساة، والزهاد من أهل الأهواء...\n\nكتاب معجز حول مستنقع الجاهلية (Câhiliye) إلى عصر السعادة (Asr-ı Saadet)، ورجال الصحراء إلى حوض الحضارة، والتعصب الأعمى إلى ينبوع الحكمة، وضحايا الشهوة إلى أبطال العفة..."
            },
            {
                id: 'k0_3',
                title_tr: "Önsöz: Genişletilmiş Yeni Baskı İçin",
                title_ing: "Foreword: For the Expanded New Edition",
                title_alm: "Vorwort: Für die erweiterte Neuauflage",
                title_arp: "مقدمة: للطبعة الجديدة الموسعة",
                tr: "Rabb'imize sonsuz hamdler olsun Kur'ân Bilinci Dersleri kitabımızın yeni ve genişletilmiş baskısı ile yeniden huzurlarınızdayız. 2015 yılında ilk olarak sizlerle buluşan bu çalışmamız, sizlerden çok yoğun bir şekilde karşılık gördü. Defaatle baskısı yapılan kitabımız, belki binlerce ders halkasında müfredat olarak okundu. Böyle bir hayrı bizlere nasip ettiği için Rabb'imize ne kadar şükür etsek azdır.\n\nŞimdi de aylardır üzerinde çalıştığımız kitabımızın bu yeni hâlini sizlere takdim etmenin heyecanı içerisindeyiz. Ümit ediyoruz ki yine sizlerden hak ettiğinden daha fazla teveccüh görecek ve hepimizin Kur'ân bilincinin tesisine ve muhafazasına biraz olsun katkı sağlayacaktır.\n\nBu yeni çalışmamızın hayırlara vesile olmasını Rabb'imizden niyaz ediyoruz. Kur'ân öyle muhteşem bir kitaptır ki onun hakkında ne yazarsanız yazın, yine eksik kalacaktır. Biz de bu kitabımızda her şeyi yazdığımızı asla iddia etmiyoruz. Tek temennimiz, aziz kitabımızın değer ve kıymetini fark etmeye biraz olsun vesile olmaktır. İnşallah ortaya konan bu gayret, böyle bir vesilenin oluşmasına katkı sağlayacaktır.\n\nSon söz yine aziz kitabımızın şu muhteşem âyeti olsun: 'Şayet yeryüzündeki ağaçlar kalem, deniz de arkasından yedi deniz katılarak (mürekkep olsa) yine Allah'ın sözleri (yazmakla) tükenmez. Şüphe yok ki Allah mutlak galip ve hikmet sahibidir.' [Lokmân 31/27].\n\nÇaba ve gayret bizden, netice ve mükafat Rabb'imizdendir.",
                ing: "Endless praise be to our Rabb, we are once again in your presence with the new and expanded edition of our Quran Consciousness Lessons book. This work, which first met you in 2015, received an intense response. Our book, which has been reprinted many times, was perhaps read as a curriculum in thousands of study circles. We cannot thank our Rabb enough for blessing us with such an immense Khayr (goodness).\n\nNow, we are excited to present you with this new version of our book, which we have been working on for months. We hope that it will once again receive more appreciation from you than it deserves and will contribute at least a little to the establishment and preservation of the Quran consciousness in all of us.\n\nWe pray to our Rabb that this new work will be a means for goodness. The Quran is such a magnificent book that no matter what you write about it, it will still remain incomplete. We never claim to have written everything in this book. Our only wish is to be a means to realize the value and worth of our beloved book. Insha'Allah, this effort will contribute to the formation of such a means.\n\nLet our final word be this magnificent verse from our beloved Book: 'And if whatever trees upon the earth were pens and the sea [was ink], replenished thereafter by seven [more] seas, the words of Allah would not be exhausted. Indeed, Allah is Exalted in Might and Wise.' [Luqman 31/27].\n\nThe effort and struggle are from us; the result and reward are from our Rabb.",
                alm: "Unendliches Lob gebührt unserem Rabb, wir sind mit der neuen und erweiterten Ausgabe unseres Buches 'Koranbewusstsein-Lektionen' wieder in Ihrer Mitte. Diese Arbeit, die Ihnen 2015 zum ersten Mal begegnete, stieß auf eine intensive Resonanz. Unser Buch, das viele Male nachgedruckt wurde, wurde vielleicht in Tausenden von Studienkreisen als Lehrplan gelesen. Wir können unserem Rabb nicht genug danken, dass Er uns mit einem so immensen Khayr (Guten) gesegnet hat.\n\nNun freuen wir uns, Ihnen diese neue Version unseres Buches vorzustellen, an der wir seit Monaten arbeiten. Wir hoffen, dass es wieder mehr Anerkennung von Ihnen erfährt, als es verdient, und dass es zumindest ein wenig zur Etablierung und Bewahrung des Koranbewusstseins in uns allen beitragen wird.\n\nWir beten zu unserem Rabb, dass dieses neue Werk ein Mittel zum Guten sein möge. Der Koran ist ein so großartiges Buch, dass es, egal was man darüber schreibt, immer unvollständig bleiben wird. Wir behaupten keineswegs, alles in diesem Buch geschrieben zu haben. Unser einziger Wunsch ist es, ein Mittel zu sein, um den Wert und die Kostbarkeit unseres geliebten Buches zu erkennen. Insha'Allah wird diese Bemühung zur Bildung eines solchen Mittels beitragen.\n\nLassen Sie unser letztes Wort dieser großartige Vers aus unserem geliebten Buch sein: 'Und wenn alle Bäume auf der Erde Schreibrohre wären und das Meer (Tinte), und nach ihm noch sieben Meere Nachschub lieferten, die Worte Allahs würden nicht zu Ende gehen. Wahrlich, Allah ist Allmächtig und Allweise.' [Luqman 31/27].\n\nDie Anstrengung und das Bemühen kommen von uns; das Ergebnis und der Lohn kommen von unserem Rabb.",
                arp: "الحمد لله رب العالمين حمداً لا يتناهى، نلتقي بكم مجدداً مع الطبعة الجديدة والموسعة من كتاب دروس وعي القرآن. هذا العمل، الذي التقى بكم لأول مرة في عام 2015، حظي باستجابة واسعة جداً. كتابنا الذي طُبع مراراً وتكراراً، ربما قُرئ كمنهج في آلاف الحلقات الدراسية. لا يسعنا أن نشكر ربنا بما فيه الكفاية على أن رزقنا مثل هذا الخير العظيم.\n\nالآن، نحن متحمسون لنقدم لكم هذه النسخة الجديدة من كتابنا الذي عملنا عليه لأشهر. نأمل أن يحظى مرة أخرى بتقديركم أكثر مما يستحق، وأن يساهم ولو قليلاً في ترسيخ وحفظ وعينا بالقرآن جميعاً.\n\nندعو ربنا أن يكون هذا العمل الجديد وسيلة للخير. القرآن كتاب عظيم لدرجة أنه مهما كتبت عنه، سيظل ناقصاً. نحن لا ندعي أبداً أننا كتبنا كل شيء في هذا الكتاب. أملنا الوحيد هو أن نكون وسيلة لإدراك قدر وقيمة كتابنا العزيز. إن شاء الله، سيساهم هذا الجهد في تكوين مثل هذه الوسيلة.\n\nلتكن كلمتنا الأخيرة هذه الآية العظيمة من كتابنا العزيز: 'وَلَوْ أَنَّمَا فِي الْأَرْضِ مِن شَجَرَةٍ أَقْلَامٌ وَالْبَحْرُ يَمُدُّهُ مِن بَعْدِهِ سَبْعَةُ أَبْحُرٍ مَّا نَفِدَتْ كَلِمَاتُ اللَّهِ ۗ إِنَّ اللَّهَ عَزِيزٌ حَكِيمٌ'. [لقمان 31/27].\n\nالجهد والسعي منا، والنتيجة والمكافأة من ربنا."
            },
            { 
                id: 'k1', 
                title_tr: "1. Ders: Kur'ân, Allah'ın (cc) Kelâmıdır", 
                title_ing: "Lesson 1: The Quran is the Word of Allah",
                title_alm: "Lektion 1: Der Koran ist das Wort Allahs",
                title_arp: "الدرس ١: القرآن كلام الله",
                tr: "İlâhî vahiy, yüce otoriteden bize süzülüp gelen Kelâm-ı Ezelî'dir. Kur'ân'ın, Allah'ın (cc) kelâmı olduğu gerçeği Kur'ân'a muhatap olan zihinlerden hiçbir zaman çıkmamalıdır. Muhatap, karşısına oturduğu kitabın sıradan bir kitap olmadığını bilmeli ve o metnin sahibinin yüceliğinin bilincinde olmalıdır.\n\nKur'ân sıradan bir roman değil, bir hikâye veya tarih kitabı değil, bir bilim veya coğrafya kitabı da değildir. Bu yüce kitap, Kelâmullah'tır. Bir hikmet ve maksat için yeryüzüne indirilmiştir. Öyleyse Kur'ân-ı Kerîm, her daim Allah'ın (cc) kelâmı olduğu bilinciyle okunmalı, saygıda kusur edilmemelidir. Ama bu saygı vahyi hayatın dışında bırakarak, saygı göstereceğiz diye ona el sürmeyecek bir hâle dönüştürmemelidir. Ona yapılacak saygı yine onun kendisinden öğrenilerek yapılmalıdır.\n\nKur'ân-ı Kerîm'in Allah'ın (cc) kelâmı olduğuna dair ilâhî üslup, ispattan ziyade nefiydir. Kur'ân, ilk muhatapları olan sahâbenin üzerinde derin değişimler meydana getirmiştir. Ancak ilâhî bir kitap insanı bu derecede değiştirir ve dönüştürür. Kur'ân-ı Kerîm'in, nâzil olduğu ilk andan itibaren imana kapılarını açmış muhatabının kalbine, ahlâkına, duruşuna çok farklı etkileri olmuştur. Çünkü o hakkı batıldan ayıran bir Furkan'dır.\n\nKelâmın Allah'a ait olduğu bilinci, muhataba çok önemli bir derinlik, teslimiyet ve İtminan kazandırır. Çünkü Kelâmullah kalplerin ilacı, zihinlerin dermanı, dillerin ise fermanıdır.",
                ing: "Divine Wahy is the Kelâm-ı Ezelî filtering down to us from the Supreme Authority. The reality that the Quran is the Kalam of Allah (cc) must never depart from the minds of those who engage with it. The addressee must realize that the book before them is not an ordinary book, and they must be profoundly conscious of the majesty of its Owner.\n\nThe Quran is not an ordinary novel, nor a storybook, nor a history book; neither is it a book of science or geography. This exalted book is Kelâmullah. It was revealed to the earth for a profound wisdom and purpose. Therefore, the Noble Quran must always be read with the consciousness that it is the Word of Allah (cc), and there must be no shortcoming in reverence towards it. However, this reverence should not turn into isolating the Wahy from life, leaving it untouched under the guise of showing respect. The true reverence to be shown to it must be learned from the Quran itself.\n\nThe divine method regarding the Noble Quran being the word of Allah (cc) is based more on negation (nefiy) than proof. The Quran brought about profound transformations upon its first addressees, the Sahaba. Only a divine book can change and transform a human being to such a degree. From the very first moment it was revealed, the Noble Quran has had remarkably distinct effects on the heart, the Akhlaq (character), and the stance of the addressee who has opened their doors to Iman. Because it is a Furkan that separates truth from falsehood.\n\nThe consciousness that this Kalam belongs to Allah grants the addressee a profound depth, absolute submission, and İtminan (tranquility). For Kelâmullah is the cure for hearts, the remedy for minds, and the divine edict for tongues.",
                alm: "Die göttliche Wahy ist der Kelâm-ı Ezelî, der von der Höchsten Autorität zu uns herabfließt. Die Realität, dass der Koran der Kalam Allahs (cc) ist, darf niemals aus den Köpfen derer verschwinden, die sich ihm zuwenden. Der Adressat muss erkennen, dass das Buch, das vor ihm liegt, kein gewöhnliches Buch ist, und er muss sich der Majestät seines Besitzers zutiefst bewusst sein.\n\nDer Koran ist kein gewöhnlicher Roman, kein Geschichten- oder Geschichtsbuch; er ist auch kein Buch über Wissenschaft oder Geografie. Dieses erhabene Buch ist Kelâmullah. Er wurde für eine tiefe Weisheit und einen bestimmten Zweck auf die Erde herabgesandt. Daher muss der Edle Koran immer mit dem Bewusstsein gelesen werden, dass er das Wort Allahs (cc) ist, und es darf kein Mangel an Ehrfurcht ihm gegenüber bestehen. Diese Ehrfurcht darf jedoch nicht dazu führen, dass die Wahy aus dem Leben verbannt wird und man sie unter dem Deckmantel des Respekts unberührt lässt. Die wahre Ehrfurcht, die ihm entgegengebracht werden muss, muss aus dem Koran selbst erlernt werden.\n\nDie göttliche Methode bezüglich der Tatsache, dass der Edle Koran das Wort Allahs (cc) ist, basiert eher auf Negation (Nefiy) als auf Beweisen. Der Koran bewirkte tiefgreifende Veränderungen bei seinen ersten Adressaten, den Sahaba. Nur ein göttliches Buch kann einen Menschen in einem solchen Maße verändern und transformieren. Vom ersten Moment seiner Offenbarung an hatte der Edle Koran bemerkenswert unterschiedliche Auswirkungen auf das Herz, den Akhlaq (Charakter) und die Haltung des Adressaten, der seine Türen für den Iman geöffnet hat. Denn es ist ein Furkan, das Wahrheit von Falschheit trennt.\n\nDas Bewusstsein, dass dieser Kalam Allah gehört, verleiht dem Adressaten eine enorme Tiefe, absolute Hingabe und İtminan (innere Ruhe). Denn Kelâmullah ist die Heilung für die Herzen, das Heilmittel für den Verstand und das göttliche Edikt für die Zungen.",
                arp: "إن الوحي الإلهي هو الكلام الأزلي (Kelâm-ı Ezelî) الذي يتنزل إلينا من السلطة العليا. إن حقيقة كون القرآن كلام الله (عز وجل) يجب ألا تغيب أبدًا عن أذهان المخاطبين به. يجب على المخاطب أن يدرك أن الكتاب الذي يجلس أمامه ليس كتابًا عاديًا، وعليه أن يكون واعيًا بعظمة صاحبه.\n\nالقرآن ليس رواية عادية، ولا كتاب قصص أو تاريخ، ولا هو كتاب علوم أو جغرافيا. هذا الكتاب الجليل هو كلام الله (Kelâmullah). لقد أُنزل إلى الأرض لحكمة وغاية عظيمة. لذلك، يجب قراءة القرآن الكريم دائمًا بوعي تام بأنه كلام الله، ولا ينبغي التقصير في احترامه وتوقيره. ولكن، لا ينبغي لهذا الاحترام أن يتحول إلى عزل الوحي عن الحياة، وتركه مهجورًا بحجة التوقير. الاحترام الحقيقي الذي يجب أن يظهر له يجب أن يُتعلم من القرآن نفسه.\n\nالأسلوب الإلهي فيما يتعلق بكون القرآن الكريم كلام الله (عز وجل) يعتمد على النفي (Nefiy) أكثر من الإثبات. لقد أحدث القرآن تغييرات عميقة في أوائل مخاطبيه من الصحابة. فقط كتاب إلهي يمكنه أن يغير الإنسان ويحوله إلى هذا الحد. منذ اللحظة الأولى لنزوله، كان للقرآن الكريم تأثيرات استثنائية على قلب وخلق وموقف المخاطب الذي فتح أبوابه للإيمان. لأنه فرقان (Furkan) يفصل الحق عن الباطل.\n\nإن الوعي بأن هذا الكلام لله يمنح المخاطب عمقًا كبيرًا، وتسليمًا مطلقًا، واطمئنانًا (İtminan). لأن كلام الله هو دواء القلوب، وبلسم العقول، وفرمان الألسنة."
            },
            {
                id: 'k2',
                title_tr: "2. Ders: Kur'ân, Allah'ın (cc) İnsan ile Diyaloğudur",
                title_ing: "Lesson 2: The Quran is Allah's Dialogue with Humanity",
                title_alm: "Lektion 2: Der Koran ist Allahs Dialog mit dem Menschen",
                title_arp: "الدرس ٢: القرآن حوار الله مع الإنسان",
                tr: "Efendimiz (sas), kutlu beyânlarının birinde der ki: 'Sizden her kim Rabb'i ile konuşmak/dertleşmek isterse hemen Kur'ân okusun.' [Deylemî, Firdevs, 1/302]. Bu hadisten de anlaşılacağı gibi Kur'ân, Allah'ın insanla ve insanın Allah'la kurduğu diyalogları dile getiren bir kitaptır. Bazen ilâhî vahiy peygamberlerle Allah arasında, bazense insanlıkla Allah arasındaki diyaloglara yer vererek ilişkinin canlılığını gözler önüne serer.\n\nVahyin kendisini dinlediğinin farkına varan; hüznünü ona açacak, sevincini onunla paylaşacak, sıkıntısını onunla giderecek, şükrünü onunla yerine getirecek, hacetini onunla isteyecek, belalarını onunla defedecek ve rahmeti onunla üzerine celbedecektir. Bunun farkına varan, o Kelâm-ı Ezelîyi okuyunca Allah'ın (cc) huzurunda olduğunu fark edecek, söylediklerine karşılık geleceğini bilecek ve Allah (cc) ile konuşmaya, dertleşmeye başlayacaktır.\n\nO rahleden artık tekdüze bir ses yükselmeyecek; cennet âyetleri duyulunca sevinilecek, cehennem âyetleri duyulunca sığınılacak, rahmet âyetlerinde simada tebessümler belirecek, azap âyetleri duyulunca gözlerden yaşlar boşanacaktır. Yani Kur'ân'la canlı, diri bir ilişki kurulacak, muhatap Allah (cc) ile konuştuğunun farkına varacak ve kalbine Sekînet inecektir.",
                ing: "Our Master (pbuh) says in one of his blessed statements: 'Whoever among you wishes to converse and confide in his Rabb, let him immediately read the Quran.' [Daylami, Firdaws, 1/302]. As understood from this Hadith, the Quran is a book that articulates the dialogues established between Allah and humanity. Sometimes the Divine Wahy presents dialogues between the Prophets and Allah, and sometimes between humanity and Allah, thereby revealing the vitality of this relationship.\n\nThe one who becomes aware that the Wahy is actually listening to them will pour out their sorrow to it, share their joy with it, cure their distress through it, fulfill their Shukr (gratitude) with it, ask for their needs through it, repel their calamities with it, and attract divine Rahmah (mercy) upon themselves through it. Realizing this, when they recite that Kelâm-ı Ezelî, they will perceive that they are in the majestic presence of Allah (cc), knowing that their words will be answered, and they will truly begin to converse and confide in Allah (cc).\n\nNo longer will a monotonous voice rise from that reading desk; there will be rejoicing when verses of Jannah are heard, refuge will be sought when verses of Jahannam are heard, smiles will appear on faces during verses of Rahmah, and tears will flow from eyes when verses of punishment are heard. A living, dynamic relationship with the Quran will be established, the addressee will realize they are speaking with Allah (cc), and Sekînet (tranquility) will descend upon their heart.",
                alm: "Unser Meister (saw) sagt in einer seiner gesegneten Aussagen: 'Wer von euch mit seinem Rabb sprechen und sich Ihm anvertrauen möchte, der soll sofort den Koran lesen.' [Daylami, Firdaws, 1/302]. Wie aus diesem Hadith hervorgeht, ist der Koran ein Buch, das die Dialoge zwischen Allah und den Menschen zum Ausdruck bringt. Manchmal präsentiert die göttliche Wahy Dialoge zwischen den Propheten und Allah und manchmal zwischen der Menschheit und Allah, wodurch die Lebendigkeit dieser Beziehung offenbart wird.\n\nDerjenige, der sich bewusst wird, dass die Wahy ihm tatsächlich zuhört, wird ihr seinen Kummer ausschütten, seine Freude mit ihr teilen, seine Not durch sie heilen, seinen Shukr (Dankbarkeit) mit ihr erfüllen, um seine Bedürfnisse durch sie bitten, seine Katastrophen mit ihr abwehren und durch sie die göttliche Rahmah (Barmherzigkeit) auf sich ziehen. Wenn er dies erkennt und jenen Kelâm-ı Ezelî rezitiert, wird er spüren, dass er sich in der majestätischen Gegenwart Allahs (cc) befindet, in dem Wissen, dass seine Worte beantwortet werden, und er wird wahrhaftig beginnen, mit Allah (cc) zu sprechen und sich Ihm anzuvertrauen.\n\nVon diesem Lesepult wird sich keine eintönige Stimme mehr erheben; man wird sich freuen, wenn Verse über Jannah gehört werden, Zuflucht suchen, wenn Verse über Jahannam gehört werden, ein Lächeln wird auf den Gesichtern erscheinen bei Versen der Rahmah, und Tränen werden aus den Augen fließen, wenn Verse der Strafe gehört werden. Eine lebendige, dynamische Beziehung zum Koran wird aufgebaut, der Adressat wird erkennen, dass er mit Allah (cc) spricht, und Sekînet (innere Ruhe) wird auf sein Herz herabkommen.",
                arp: "يقول سيدنا (صلى الله عليه وسلم) في أحد بياناته المباركة: 'من أراد منكم أن يناجي ربه ويتحدث إليه فليقرأ القرآن فورًا'. [الديلمي، الفردوس، 1/302]. كما يُفهم من هذا الحديث، فإن القرآن كتاب يعبر عن الحوارات التي يقيمها الله مع الإنسان. أحيانًا يعرض الوحي الإلهي حوارات بين الأنبياء والله، وأحيانًا بين البشرية جمعاء والله، مما يبرز حيوية هذه العلاقة.\n\nمن يدرك أن الوحي يستمع إليه حقًا؛ سيبث إليه حزنه، ويشاركه فرحه، ويزيل به ضيقه، ويؤدي شكره به، ويطلب حاجته من خلاله، ويدفع به بلاءه، ويستجلب به رحمة الله عليه. من يدرك هذا، عندما يتلو ذلك الكلام الأزلي (Kelâm-ı Ezelî)، سيشعر بأنه في حضرة الله (عز وجل)، وسيعلم أن كلماته ستُجاب، وسيبدأ حقًا في مناجاة الله والتحدث إليه.\n\nلن يرتفع بعد الآن صوت رتيب من تلك المنصة؛ بل سيكون هناك فرح عند سماع آيات الجنة، وسيُطلب اللجوء عند سماع آيات جهنم، وستظهر الابتسامات على الوجوه عند آيات الرحمة، وستذرف الدموع من العيون عند سماع آيات العذاب. ستُقام علاقة حية ومفعمة بالحيوية مع القرآن، وسيدرك المخاطب أنه يتحدث مع الله (عز وجل)، وستتنزل السكينة (Sekînet) على قلبه."
            }
        ] 
    },
    sunnet: { title: "Sünnet Bilinci", subtitle: "Nebevi Rehberlik", symbol: '☀', chapters: [] },
    siyer: { title: "Siyer Bilinci", subtitle: "Hz. Muhammed'in (sav) İzinde", symbol: '☾', chapters: [] },
    sahabe: { title: "Sahâbe Bilinci", subtitle: "Yıldız Nesil", symbol: '★', chapters: [] }
};
